# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.9
  - 3.8
  - 3.7

services:
  - docker

before_install:
  - docker pull mongo
  - docker run -d -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=SimpleJWT_MongoEngine mongo

install:
  - pip install -U tox-travis

script: tox
