name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    if: github.repository == 'ngocngoan/djangorestframework-simplejwt-mongoengine'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U setuptools twine wheel build

      - name: Build package
        run: |
          python setup.py --version
          python -m build
          twine check dist/*

      - name: Publish packages
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.RELEASE_KEY }}
