name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    if: github.repository == 'ngocngoan/djangorestframework-simplejwt-mongoengine'
    runs-on: ubuntu-latest
		permissions:
			# IMPORTANT: this permission is mandatory for trusted publishing
			id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get install -y gettext
          python -m pip install -U pip
          python -m pip install -U setuptools twine wheel
          pip install -e .[dev]

      - name: Check locale
        working-directory: rest_framework_simplejwt_mongoengine
        run: |
          echo "Checking if locale files need updating. If they do, cd rest_framework_simplejwt_mongoengine && run python ../scripts/i18n_updater.py"
          python ../scripts/i18n_updater.py
          git diff --exit-code

      - name: Build package
        run: |
          python setup.py --version
          python setup.py sdist --format=gztar bdist_wheel
          twine check dist/*

      - name: Publish packages
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.RELEASE_KEY }}
